import { Media } from './Gallery';

export const media: Media[] = [
  {
    type: 'image',
    group: 'work',
    caption: 'Star Citizen Field Guide Ships',
    source: { regular: '/images/apps/star_citizen_app_ship.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: 'Star Citizen Field Guide System',
    source: { regular: '/images/apps/star_citizen_app_systems.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/apps/star_citizen_app_gallery.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: 'Star Citizen Field Guide Comm Link',
    source: { regular: '/images/apps/star_citizen_app_commlink.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: 'Star Citizen Field Guide About Screen',
    source: { regular: '/images/apps/star_citizen_app_about.jpg' },
  },

  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/boppl.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/boppl_admin_1.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/boppl_admin_2.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/boppl_admin_3.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/boppl_venues.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/prism_digital_1.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/prism_digital_2.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/prism_digital_3.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/simply_sleep_time.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/websites/winops.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/princessandfrog.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/treasures.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/pquizzy.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/jubjub.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/g5.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/g52.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/icarlyremote.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/babyspencer.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/adrenalingames.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/jane.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/donethat.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/scoobydoo.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/tangrams.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/wordcracker.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/hex.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/chowder.jpg' },
  },
  {
    type: 'video',
    group: 'work',
    caption: '',
    source: { regular: '/http://www.youtube.com/watch?v=vdPxVP7Mfec&feature=youtu.be' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/fyp_city.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/lighting1.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/lighting2.jpg' },
  },
  {
    type: 'video',
    group: 'work',
    caption: '',
    source: { regular: '/http://www.youtube.com/watch?v=BkMrVkC7JLU' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/lowpolyseen2.jpg' },
  },
  {
    type: 'video',
    group: 'work',
    caption: '',
    source: { regular: '/http://www.youtube.com/watch?v=PuP9d-Sdt5w' },
  },
  {
    type: 'video',
    group: 'work',
    caption: '',
    source: { regular: '/www.youtube.com/watch?v=Z_phgn1_MKQ' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/item47.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/bunker.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/train.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/dawning.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/thestrip.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/immunization.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/quicksand.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/towers.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/dirt.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/monstermunch.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/rivercrossing.jpg' },
  },
  {
    type: 'image',
    group: 'work',
    caption: '',
    source: { regular: '/images/art/stars.jpg' },
  },
];
